// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqUBX83bc5PKLewLwG_xblRe4UPH6jCwo',
    appId: '1:334111310983:web:9c0a0d3aae69426a6de422',
    messagingSenderId: '334111310983',
    projectId: 'app-playground-3b06a',
    authDomain: 'app-playground-3b06a.firebaseapp.com',
    storageBucket: 'app-playground-3b06a.appspot.com',
    measurementId: 'G-WR4VDL9JL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCchdGfrvHsRdw-TpQ4sEBH8O82n5WTRus',
    appId: '1:334111310983:android:6cab45b989817e8f6de422',
    messagingSenderId: '334111310983',
    projectId: 'app-playground-3b06a',
    storageBucket: 'app-playground-3b06a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT_CozdR7rl62NJb8II3yHS2Kwt0sv_us',
    appId: '1:334111310983:ios:b3128402f4da48ea6de422',
    messagingSenderId: '334111310983',
    projectId: 'app-playground-3b06a',
    storageBucket: 'app-playground-3b06a.appspot.com',
    iosClientId: '334111310983-r1psd0ik06q0a0gecqaq7u94ubbcfgu9.apps.googleusercontent.com',
    iosBundleId: 'com.aplayground',
  );
}
